name: Minify JS
on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # checkout repo
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      # run minify action to minify js in given directory
      - name: Auto Minify
        uses: nizarmah/auto-minify@v2.1
        with:
          # directory to minify
          directory: 'assets'

      # commit changes, push minified files to repo
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          # commit message, change as needed
          commit_message: "adds minified js"
